DROP TABLE IF EXISTS Trains.PassengerRoute;
DROP TABLE IF EXISTS Trains.Car;
DROP TABLE IF EXISTS Trains.[Route];
DROP TABLE IF EXISTS Trains.CarType;
DROP TABLE IF EXISTS Trains.Train;
DROP TABLE IF EXISTS Trains.Passenger;

